train <- read.csv('train.csv',header = TRUE)
test <- read.csv('test.csv', header = TRUE)
test.survived <- data.frame(Survived= rep('None', nrow(test)), test[,])
dat.combined <- rbind(train, test.survived)
str(dat.combined)
dat.combined$Pclass<- as.factor(dat.combined$Pclass)
dat.combined$Survived<- as.factor(dat.combined$Survived)
