train <- read.csv('train.csv',header = TRUE)
test <- read.csv('test.csv', header = TRUE)
test.survived <- data.frame(Survived= rep('None', nrow(test)), test[,])
dat.combined <- rbind(train, test.survived)
str(dat.combined)
dat.combined$Pclass<- as.factor(dat.combined$Pclass)
dat.combined$Survived<- as.factor(dat.combined$Survived)
table(dat.combined$Survived)
table(dat.combined$Pclass)
library(ggplot2)
train$Pclass<-as.factor(train$Pclass)
str(train)
ggplot(train, aes(x=Pclass, fill=factor(Survived))) +  geom_bar()
length(unique(as.character(dat.combined$Name)))
dup.names <- as.character(dat.combined[which(duplicated(as.character(dat.combined$Name))),"Name"])
